version: '3.8'

services:
  # Основное приложение
  app:
    build: .
    container_name: linda_sza_app
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - app-network

  # Nginx для проксирования и статических файлов
  nginx:
    image: nginx:alpine
    container_name: linda_sza_nginx
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./images:/usr/share/nginx/html/images
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  images:
  data:
